theme: jekyll-theme-cayman
title: [Sidra Sohail]
description: [I'm a graduate research assistant pursuing a M.S. in Bioinformatics at Loyola University Chicago.]
<!DOCTYPE html>
<html>
<body>
<h2><strong>Hi Sidra Sohail...<strong></h2>

<p><b>Research Assistant | M.S. Bioinformatics | Burns Lab <b></p>

<img src="Sidra.png" style="float:left;width:400px;height:400px;">

</body>
<html>
